# Generated by Django 4.1.2 on 2022-11-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                ("opening_time", models.TimeField(verbose_name="opening_time")),
                ("closing_time", models.TimeField(verbose_name="closing_time")),
                ("active", models.BooleanField(verbose_name="active")),
            ],
        ),
    ]
