# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: restaurants/grpc/restaurants.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder


# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\"restaurants/grpc/restaurants.proto\x12\x0ftdd.restaurants\"\x17\n\x15RestaurantListRequest\"N\n\x16RestaurantListResponse\x12\x34\n\x07results\x18\x01 \x03(\x0b\x32#.tdd.restaurants.RestaurantResponse\"k\n\x12RestaurantResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0copening_time\x18\x03 \x01(\t\x12\x14\n\x0c\x63losing_time\x18\x04 \x01(\t\x12\x0f\n\x07is_open\x18\x05 \x01(\x08\"\'\n\x19RestaurantRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xd0\x01\n\x14RestaurantController\x12Y\n\x04List\x12&.tdd.restaurants.RestaurantListRequest\x1a\'.tdd.restaurants.RestaurantListResponse\"\x00\x12]\n\x08Retrieve\x12*.tdd.restaurants.RestaurantRetrieveRequest\x1a#.tdd.restaurants.RestaurantResponse\"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'restaurants.grpc.restaurants_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _RESTAURANTLISTREQUEST._serialized_start = 55
    _RESTAURANTLISTREQUEST._serialized_end = 78
    _RESTAURANTLISTRESPONSE._serialized_start = 80
    _RESTAURANTLISTRESPONSE._serialized_end = 158
    _RESTAURANTRESPONSE._serialized_start = 160
    _RESTAURANTRESPONSE._serialized_end = 267
    _RESTAURANTRETRIEVEREQUEST._serialized_start = 269
    _RESTAURANTRETRIEVEREQUEST._serialized_end = 308
    _RESTAURANTCONTROLLER._serialized_start = 311
    _RESTAURANTCONTROLLER._serialized_end = 519
# @@protoc_insertion_point(module_scope)
