# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from restaurants.grpc import restaurants_pb2 as restaurants_dot_grpc_dot_restaurants__pb2


class RestaurantControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
            '/tdd.restaurants.RestaurantController/List',
            request_serializer=restaurants_dot_grpc_dot_restaurants__pb2.RestaurantListRequest.SerializeToString,
            response_deserializer=restaurants_dot_grpc_dot_restaurants__pb2.RestaurantListResponse.FromString,
        )
        self.Retrieve = channel.unary_unary(
            '/tdd.restaurants.RestaurantController/Retrieve',
            request_serializer=restaurants_dot_grpc_dot_restaurants__pb2.RestaurantRetrieveRequest.SerializeToString,
            response_deserializer=restaurants_dot_grpc_dot_restaurants__pb2.RestaurantResponse.FromString,
        )


class RestaurantControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestaurantControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'List': grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=restaurants_dot_grpc_dot_restaurants__pb2.RestaurantListRequest.FromString,
            response_serializer=restaurants_dot_grpc_dot_restaurants__pb2.RestaurantListResponse.SerializeToString,
        ),
        'Retrieve': grpc.unary_unary_rpc_method_handler(
            servicer.Retrieve,
            request_deserializer=restaurants_dot_grpc_dot_restaurants__pb2.RestaurantRetrieveRequest.FromString,
            response_serializer=restaurants_dot_grpc_dot_restaurants__pb2.RestaurantResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler('tdd.restaurants.RestaurantController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class RestaurantController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tdd.restaurants.RestaurantController/List',
            restaurants_dot_grpc_dot_restaurants__pb2.RestaurantListRequest.SerializeToString,
            restaurants_dot_grpc_dot_restaurants__pb2.RestaurantListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Retrieve(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tdd.restaurants.RestaurantController/Retrieve',
            restaurants_dot_grpc_dot_restaurants__pb2.RestaurantRetrieveRequest.SerializeToString,
            restaurants_dot_grpc_dot_restaurants__pb2.RestaurantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
